name = "chromatic.pink"
author = "chromaetheral"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e11972c2950b0693d03c6cb8653b5147d3ad0492e72b328f061da85f7daff8c"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20–1.20.1", "1.20"]
