name = "chromatic.pink"
author = "chromaetheral"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feb229bc6600d3e426d51fd3b46916f19354efabf0b429ff5472d598503be36f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20–1.20.1", "1.20"]
