name = "chromatic.pink"
author = "chromaetheral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aaa42426d034a120bce3a99604bb283f0921bbc8a2838c8a9ec6cacc79f9069"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
