name = "chromatic.pink"
author = "chromaetheral"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1825cf3b64be2f72c4ed10cb21e666352475a8b5342da11cd60ff8ca090327e9"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
