name = "chromatic.pink"
author = "chromaetheral"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb49010219e97e4c4abe1ae80c93e62727ad66121ded4be6bc3d419912692a29"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20–1.20.1", "1.20"]
