name = "chromatic.pink"
author = "chromaetheral"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65085dcc2b30fc43c466c423dbceb3b6153daeb26ad6e4f51cbe2f105c1b12b2"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
