name = "chromatic.pink"
author = "chromaetheral"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db8a43805e4b9808c78e0ba3e652bc5a22ba7cea3718b227112a58a2659614b3"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20–1.20.1", "1.20"]
