name = "chromatic.pink"
author = "chromaetheral"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6086acfff2d9c7e9acb42c46b1c696d654cff0b21cfc663fc22a08befc66ae7e"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20–1.20.1", "1.20"]
