name = "chromatic.pink"
author = "chromaetheral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c6e9cabbef9098374b6edd11b1e40e4907b92a521e25a503b17cbaec5261db4"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
