name = "chromatic.pink"
author = "chromaetheral"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8775424a7cc9f0f94c1da895f996fdc59bc062a78031812ad04f69c43650abae"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
