name = "chromatic.pink"
author = "chromaetheral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a65cd944d6c162a0418e5d0779db654c7eafe908811bb052ced20154f984297"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
