name = "chromatic.pink"
author = "chromaetheral"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c86228f4add2170b93ce75b6602a944ab0364874c29dc09571f872c9c65a073a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
