name = "chromatic.pink"
author = "chromaetheral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64d49b5b15fc1caade20dcd119a451be2830d1cb5fc417d6838980e547033293"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
