name = "chromatic.pink"
author = "chromaetheral"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c41f720a9b2e254350ceaada9af89353b921ce64b05f90d4eaf6c9af5b606429"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
