name = "chromatic.pink"
author = "chromaetheral"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9414f775309b48b8158a04ddfee60b943981ae7a0c9257c955865256f9d59e5a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
