name = "chromatic.pink"
author = "chromaetheral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0380cb75c70866852f3e9491964c11d52d644245c9f3619c20f7522c96d09fcc"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
