#If debug mode is active, the mod will log when items are dropped
debugMode = false
#Items to add, in the form modid:itemName:[nbtfile]:minStackSize:maxStackSize:universalChance:[monsterChance]:[bossChance]:[group1Chance]:[group2Chance]...
#Chances are %
#NBT File is a json file in the "editmobdrops" folder here in config (leave blank for none)
itemsToAdd = ["minecraft:ender_pearl::1:1:0:0:50:0", "minecraft:ender_pearl::1:2:0:0:0:80"]
#Mob groups, in the form [EntityModid]:[EntityName]:[EntityModid]:[EntityName]...
mobGroups = ["farlanders:enderminion:farlanders:mystic_enderminion:farlanders:ender_guardian:farlanders:looter:farlanders:rebel", "farlanders:mystic_enderman:farlanders:ender_golem:farlanders:fanmade_enderman"]
#Mobs to clear existing drops from
mobsToClear = []
#Single mob items, in the form EntityModid:EntityName:modid:itemName:[nbtfile]:minStackSize:maxStackSize:chance
singleMobItems = ["farlanders:titan:minecraft:ender_pearl::3:4:100"]
