
[general]
	#Colors must be specified in #RRGGBB format
	"color values" = ["#BFBFBF", "#ff27be", "#5c5c5c", "#9c1b75", "#242424", "#4e0a3a"]
	#Always show armor bar even if empty?
	"Always show bar" = false
	#Show empty armor icons?
	"Show empty icons" = false

